name: Rebuild all releases

on:
  workflow_dispatch:

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Rebuild releases
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git fetch --tags
          releases=$(gh release list --exclude-drafts --exclude-pre-releases -R erlang/otp --limit 50 | cut -f 3)

          for release in $releases
          do
            if git rev-parse "$release" -- >/dev/null 2>&1;
            then
              echo "Triggering rebuild of release $release"
              gh workflow run build.yml -f otp_version="${release#OTP-}"
            else
              echo "Releas $release exists, but there is no associated tag for it."
            fi
          done
